{{- range .Values.segments }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-pv-reclaim-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: pv-patcher
      restartPolicy: Never
      containers:
      - name: patch-pv
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for PVCs to be bound..."
          sleep 10

          # Get PV names for this segment
          ZONES_PV=$(kubectl get pvc zones-unified-dns-dhcp-{{ .name }}-0 -n {{ $.Values.global.namespace }} -o jsonpath='{.spec.volumeName}' 2>/dev/null || echo "")
          LEASES_PV=$(kubectl get pvc kea-leases-unified-dns-dhcp-{{ .name }}-0 -n {{ $.Values.global.namespace }} -o jsonpath='{.spec.volumeName}' 2>/dev/null || echo "")

          # Patch zones PV
          if [ -n "$ZONES_PV" ]; then
            echo "Patching zones PV: $ZONES_PV"
            kubectl patch pv "$ZONES_PV" -p '{"spec":{"persistentVolumeReclaimPolicy":"{{ $.Values.global.storage.reclaimPolicy }}"}}' || true
          else
            echo "Warning: zones PVC not found for segment {{ .name }}"
          fi

          # Patch leases PV
          if [ -n "$LEASES_PV" ]; then
            echo "Patching leases PV: $LEASES_PV"
            kubectl patch pv "$LEASES_PV" -p '{"spec":{"persistentVolumeReclaimPolicy":"{{ $.Values.global.storage.reclaimPolicy }}"}}' || true
          else
            echo "Warning: leases PVC not found for segment {{ .name }}"
          fi

          echo "PV reclaim policy patching completed for segment {{ .name }}"
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-patcher
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-patcher
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-patcher-{{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-patcher
subjects:
- kind: ServiceAccount
  name: pv-patcher
  namespace: {{ .Values.global.namespace }}
