{{- range .Values.segments }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unified-dns-dhcp-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: unified-dns-dhcp
    segment: "{{ .name }}"
spec:
  serviceName: unified-dns-dhcp-{{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: unified-dns-dhcp
      segment: "{{ .name }}"
  template:
    metadata:
      labels:
        app: unified-dns-dhcp
        segment: "{{ .name }}"
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "mam-hh-{{ .name }}",
              "ips": ["{{ .ipv4.dhcp }}/24", "{{ .ipv6.dhcp }}/64"]
            }
          ]
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
      {{- include "containers.init.routes" (dict "network" $.Values.network) | nindent 6 }}
      {{- if $.Values.services.dns.enabled }}
      {{- include "containers.init.zones" . | nindent 6 }}
      {{- if eq ($.Values.global.resolver.type | default "knot") "unbound" }}
      {{- include "containers.init.unbound" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
      {{- if $.Values.services.dns.enabled }}
      {{- if eq ($.Values.global.resolver.type | default "knot") "knot" }}
      {{- include "containers.knot.resolver" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- else if eq $.Values.global.resolver.type "unbound" }}
      {{- include "containers.unbound" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- end }}

      {{- if eq ($.Values.global.authDNS.type | default "knot") "bind" }}
      {{- include "containers.bind.auth" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- else }}
      {{- include "containers.knot.auth" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- end }}
      {{- end }}

      {{- if $.Values.services.dhcp.enabled }}
      {{- include "containers.kea.dhcp4" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- include "containers.kea.ddns" (dict "images" $.Values.global.images) | nindent 6 }}
      {{- end }}

      volumes:
      - name: config
        configMap:
          name: unified-dns-dhcp-{{ .name }}-config
      {{- if and $.Values.services.dns.enabled (eq ($.Values.global.resolver.type | default "knot") "unbound") }}
      - name: unbound-data
        emptyDir: {}
      {{- end }}
  volumeClaimTemplates:
  {{- if $.Values.services.dns.enabled }}
  - metadata:
      name: zones
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi
  {{- end }}
  {{- if $.Values.services.dhcp.enabled }}
  - metadata:
      name: kea-leases
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi
  {{- end }}
  {{- if and $.Values.stork.enabled $.Values.stork.agent.enabled }}
  - metadata:
      name: stork-agent-data
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Mi
  {{- end }}
{{- end }}
