{{- range .Values.segments }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unified-dns-dhcp-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: unified-dns-dhcp
    segment: "{{ .name }}"
spec:
  serviceName: unified-dns-dhcp-{{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: unified-dns-dhcp
      segment: "{{ .name }}"
  template:
    metadata:
      labels:
        app: unified-dns-dhcp
        segment: "{{ .name }}"
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "mam-hh-{{ .name }}",
              "ips": ["{{ .ipv4.dhcp }}/24", "{{ .ipv6.dhcp }}/64"]
            }
          ]
    spec:
      initContainers:
      # Fix routing: set higher metric on eth0 so net1 is always preferred
      - name: init-routes
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          # Remove the default route via eth0
          ip route del default via 10.42.0.1 dev eth0 || true
          # Re-add it with a higher metric (100) so it's only used as backup
          ip route add default via 10.42.0.1 dev eth0 metric 100
          echo "Routes configured:"
          ip route
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      {{- if $.Values.services.dns.enabled }}
      - name: init-zones
        image: busybox
        command: ['sh', '-c', 'cp /config-init/*.zone /zones/ || true']
        volumeMounts:
        - name: zones
          mountPath: /zones
        - name: config
          mountPath: /config-init
      {{- if eq ($.Values.global.resolver.type | default "knot") "unbound" }}
      - name: init-unbound
        image: {{ $.Values.global.images.unbound }}
        command: ['sh', '-c']
        args:
        - |
          # Create unbound directories
          mkdir -p /var/lib/unbound
          # Initialize trust anchor if it doesn't exist
          if [ ! -f /var/lib/unbound/root.key ]; then
            unbound-anchor -a /var/lib/unbound/root.key || true
          fi
        volumeMounts:
        - name: unbound-data
          mountPath: /var/lib/unbound
      {{- end }}
      {{- end }}
      containers:
      {{- if $.Values.services.dns.enabled }}
      {{- if eq ($.Values.global.resolver.type | default "knot") "knot" }}
      - name: knot-resolver
        image: {{ $.Values.global.images.knotResolver }}
        command: ["sh", "-c"]
        args: 
        - |
          exec /usr/sbin/kresd -c /etc/knot-resolver/kresd.conf -n
        ports:
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        - containerPort: 8453
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: config
          mountPath: /etc/knot-resolver/kresd.conf
          subPath: kresd.conf
      {{- else if eq $.Values.global.resolver.type "unbound" }}
      - name: unbound
        image: {{ $.Values.global.images.unbound }}
        command: ["sh", "-c"]
        args:
        - |
          exec unbound -d -c /etc/unbound/unbound.conf
        ports:
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        - containerPort: 8953
          protocol: TCP
          name: control
        volumeMounts:
        - name: config
          mountPath: /etc/unbound/unbound.conf
          subPath: unbound.conf
        - name: unbound-data
          mountPath: /var/lib/unbound
      {{- end }}
      
      - name: knot-auth
        image: {{ $.Values.global.images.knotAuth }}
        command: ["/usr/sbin/knotd"]
        args: ["-c", "/etc/knot/knot.conf"]
        ports:
        - containerPort: 5353
          protocol: UDP
          name: auth-dns-udp
        - containerPort: 5353
          protocol: TCP
          name: auth-dns-tcp
        volumeMounts:
        - name: config
          mountPath: /etc/knot/knot.conf
          subPath: knot.conf
        - name: zones
          mountPath: /var/lib/knot/zones
      {{- end }}
      {{- if $.Values.services.dhcp.enabled }}
      - name: kea-dhcp4
        image: {{ $.Values.global.images.keaDhcp }}
        command: ["/usr/sbin/kea-dhcp4"]
        args: ["-c", "/etc/kea/kea-dhcp4.conf"]
        securityContext:
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]
        volumeMounts:
        - name: config
          mountPath: /etc/kea/kea-dhcp4.conf
          subPath: kea-dhcp4.conf
        - name: kea-leases
          mountPath: /var/lib/kea
      
      - name: kea-ddns
        image: {{ $.Values.global.images.keaDdns }}
        command: ["/usr/sbin/kea-dhcp-ddns"]
        args: ["-c", "/etc/kea/kea-dhcp-ddns.conf"]
        volumeMounts:
        - name: config
          mountPath: /etc/kea/kea-dhcp-ddns.conf
          subPath: kea-dhcp-ddns.conf
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: unified-dns-dhcp-{{ .name }}-config
      {{- if and $.Values.services.dns.enabled (eq ($.Values.global.resolver.type | default "knot") "unbound") }}
      - name: unbound-data
        emptyDir: {}
      {{- end }}
  volumeClaimTemplates:
  {{- if $.Values.services.dns.enabled }}
  - metadata:
      name: zones
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi
  {{- end }}
  {{- if $.Values.services.dhcp.enabled }}
  - metadata:
      name: kea-leases
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi
  {{- end }}
{{- end }}
